- app/models/friendship.rb
- app/models/user.rb
- db/migrate/20200922061707_add_username_to_user.rb
- db/migrate/20200922062103_create_friendships.rb
- db/schema.rb
- test/models/friendship_test.rb
Added user and friendship models
> Added user and friendship models

- Gemfile
- Gemfile.lock
- app/controllers/users_controller.rb
- app/views/users/friends.html.erb
- config/routes.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/users_controller_test.rb
1. Added my user (ytf@email.com)
2. Added a line for randomly generated users to befriend @yongtaufoo user
> Fixed seed data to make random users befriend ytf (my user)

- app/assets/stylesheets/components/_carousel.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_text.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/users/friends.html.erb
- config/environments/development.rb
1. Created components we need 
2. Draft for carousel
> Components and Carousel

- app/assets/stylesheets/components/_carousel.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_scrollable.scss
- app/models/user.rb
- app/views/users/friends.html.erb
- db/seeds.rb
1. Done with first draft of scrollable section
> Draft friends page

- app/assets/stylesheets/components/_scrollable.scss
- app/assets/stylesheets/components/_search.scss
- app/views/shared/_search_bar.html.erb
- app/views/users/friends.html.erb
Fixed mobile view for Friends page
> Fixing mobile visible areas

- app/javascript/packs/application.js
- app/javascript/plugins/init_masonry_layout.js
- app/views/layouts/application.html.erb
- app/views/memories/index.html.erb
Fixed javascript for masonry layout
> fixed hard refresh issue

- app/assets/stylesheets/components/_custom-containers.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_text.scss
- app/views/devise/sessions/new.html.erb
> Improved login page

- app/assets/stylesheets/components/_custom-containers.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_image.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_scrollable.scss
- app/assets/stylesheets/components/_search.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_memories_show.scss
- app/controllers/memories_controller.rb
- app/views/layouts/application.html.erb
- app/views/memories/index.html.erb
- app/views/memories/show.html.erb
- db/seeds.rb
1. Added memory show page
2. Created link from community page to memory show page
3. Updated margins on community page
4. Corrected landscape view of friends and community page.
> Added Memory Show Page and Fixed Landscape View

- app/views/devise/sessions/new.html.erb
- app/views/layouts/application.html.erb
1. Removed navbar from login page
2. Changed navbar login button to 100% width
> Removed navbar from login page

- app/controllers/memories_controller.rb
- app/views/memories/_ar_overlay.html.erb
- app/views/memories/_ar_scene.html.erb
- app/views/users/friends.html.erb
Import button from Friends page now updated to send instance(s) of user avatar instead of cloudinary key(s)
> updated import to camera method

- app/assets/stylesheets/components/_custom-containers.scss
- app/assets/stylesheets/components/_image.scss
- app/assets/stylesheets/pages/_memories_show.scss
- app/models/memory.rb
- app/views/layouts/application.html.erb
- app/views/memories/show.html.erb
Added time since upload for memories show page
> Add memories time

- app/javascript/plugins/init_collapse_camera_view_elements.js
- db/schema.rb
Fixed error messages for collapse camera element js
> fixed js error messages

- app/javascript/aframe/components/avatar-component.js
- app/javascript/aframe/systems/ar-hit-test-system.js
- app/javascript/aframe/systems/avatar-system.js
- app/javascript/controllers/ar_overlay_controller.js
- app/javascript/packs/aframe-pack.js
- app/views/memories/_ar_overlay.html.erb
- app/views/memories/_ar_scene.html.erb
Added avatar system to manage avatars
> AR Reset Button Implementation

- app/assets/stylesheets/pages/_memories_show.scss
- app/controllers/memories_controller.rb
- app/views/memories/show.html.erb
Also made some changes to show page view
> Community page now has mine and my friends' memories 

- app/assets/stylesheets/components/_ar-overlay.scss
- app/assets/stylesheets/components/_image.scss
- app/assets/stylesheets/components/_photo-preview.scss
- app/controllers/memories_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_collapse_camera_view_elements.js
- app/javascript/plugins/init_modal_trigger.js
- app/views/memories/_ar_overlay.html.erb
- app/views/shared/_camera_shutter_with_collapse_btn.erb
- app/views/shared/_photo_preview.html.erb
Added upload button and upload form for photo
> Add upload btn to camera

- app/assets/stylesheets/components/_notifications.scss
- app/assets/stylesheets/pages/_memories_show.scss
- app/controllers/comments_controller.rb
- app/controllers/memories_controller.rb
- app/models/comment.rb
- app/models/memory.rb
- app/models/user.rb
- app/views/memories/show.html.erb
- config/routes.rb
- db/migrate/20200929101633_create_comments.rb
- db/schema.rb
- test/controllers/comments_controller_test.rb
- test/models/comment_test.rb
> Show page now has comments feature

- app/views/memories/_ar_overlay.html.erb
Button to trigger hide all camera action elements is added in the ar_overlay
> Added a button on ar_overlay to trigger collapse

- app/controllers/users_controller.rb
- db/seeds.rb
1. Created avatars and memories linked to specific avatars
> Memories seed

- app/views/devise/sessions/new.html.erb
> Fixed favicon

- app/assets/stylesheets/components/_header.scss
- app/views/layouts/application.html.erb
- app/views/memories/index.html.erb
- app/views/pages/notifications.html.erb
- app/views/shared/_header.html.erb
- app/views/users/friends.html.erb
Added user avatar on right corner of the header. User can now logout by selecting dropdown item 'logout'.
> Added user avatar on header with dropdown

- app/controllers/notifications_controller.rb
- app/controllers/pages_controller.rb
- app/models/friendship.rb
- app/models/notification.rb
- app/models/user.rb
- app/views/notifications/index.html.erb
- config/routes.rb
- db/migrate/20200926143511_create_notifications.rb
- db/migrate/20200926150207_change_read_in_notifications.rb
- db/migrate/20200926150540_add_references_to_notifications.rb
- db/migrate/20200926151514_add_content_to_notifications.rb
- db/seeds.rb
- test/controllers/notifications_controller_test.rb
- test/models/notification_test.rb
Correct branch with the changes required for reciprocal friendships
> Fixed two-way friendships

- app/javascript/packs/application.js
- app/views/users/friends.html.erb
> Fixed the counter issue, removed the extra import button

- db/seeds.rb
Added Jade to our seed; changed beach picture
> Added Jade

- app/controllers/comments_controller.rb
- app/controllers/memories_controller.rb
- app/views/memories/show.html.erb
1. Comments are in ascending order
2. Comments now anchor to the latest comment
> Comments are in ascending order
